services:
  nginx:
    container_name: 'nginx'
    build:
      context: .
      dockerfile: nginx/nginx.dockerfile
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./nginx/certs:/etc/nginx/certs
    links:
      - web:web
    depends_on:
      - web
    ports:
      - "8080:80"
      - "8083:443"
    networks:
      - app-network
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-network
    ports:
      - "5433:5432"
  web:
    container_name: 'web'
    build: .
    command: gunicorn -b "0.0.0.0:8000" app.wsgi
    volumes:
      - .:/code
    expose:
      - 8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge